image:
  registry: docker.io
  repository: gitea/gitea
  tag: 1.22.3
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  ports: 
    http: 3000
  ssh:
    enabled: true
    service:
      type: ClusterIP
      port: 22

postgresql-ha:
  enabled: true
  
  pgpool:
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 512Mi
  
  persistence:
    storageClass: "truenas-nfs"
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    
  global:
    storageClass: "truenas-nfs"

gitea:
  admin:
    username: gitea-admin
    password: "ChangeMeStrongPassword!"
    email: "admin@gitea.devsecmindset.dev"
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 768Mi
  
  config:
    database:
      DB_TYPE: postgres
      HOST: "gitea-prod-postgresql-ha-pgpool.default.svc.cluster.local:5432"
      NAME: gitea
      USER: gitea
      PASSWD: gitea
      SSL_MODE: disable
    server:
      ROOT_URL: "https://gitea.devsecmindset.dev/"
      DOMAIN: "gitea.devsecmindset.dev"
      SSH_DOMAIN: "gitea.devsecmindset.dev"
      HTTP_PORT: 3000
      SSH_PORT: 22
    service:
      DISABLE_REGISTRATION: true
  
  initContainers:
    enabled: false
  
  createSecret: false
#  existingSecret: gitea-prod

persistence:
  enabled: true
  size: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClass: "local-path"

pdb:
  create: false 
  minAvailable: 1

networkPolicy:
  enabled: false 

externalDatabase:
  existingSecret: ""

volumePermissions:
  enabled: false 

global:
  imagePullSecrets: []