persistence:
  enabled: true
  size: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClass: "local-path"

gitea:
  admin:
    username: admin
    password: "ChangeMeStrongPassword!"
    email: "admin@gitea.devsecmindset.dev"

  config:
    database:
      DB_TYPE: postgres
      HOST: "gitea-prod-postgresql-ha-pgpool.default.svc.cluster.local:5432"
      NAME: gitea
      USER: gitea
      PASSWD: gitea
      SSL_MODE: disable

    server:
      ROOT_URL: "https://gitea.devsecmindset.dev/"
      DOMAIN: "gitea.devsecmindset.dev"
      SSH_DOMAIN: "gitea.devsecmindset.dev"
      HTTP_PORT: 3000
      SSH_PORT: 22

    service:
      DISABLE_REGISTRATION: true

service:
  http:
    type: ClusterIP
    port: 3000

ssh:
  enabled: true
  service:
    type: ClusterIP
    port: 22
