controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
    pullPolicy: "IfNotPresent"

  admin:
    username: "admin"
    password: "ChangeMeStrongPassword!"

  serviceType: ClusterIP

  installPlugins:
    - kubernetes:latest
    - git:latest
    - workflow-aggregator:latest
    - configuration-as-code:latest

  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to Jenkins in Kubernetes, deployed with Ansible!"

persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: "local-path"

service:
  type: ClusterIP
  port: 8080
